language: python
python:
  - "2.7"
env:
  - DJANGO=1.5
  - DJANGO=1.6.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q nose django-nose --use-mirrors
  - pip install -q coverage coveralls --use-mirrors
  - pip install -e . --use-mirrors
script:
  - coverage run --source klingon setup.py test
after_success:
  - coveralls
