language: python
sudo: false
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO<1.6
  - DJANGO<1.7
  - DJANGO<1.8
  - DJANGO<1.9
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements-test.txt
  - pip install -e .
script:
  - coverage run --source klingon setup.py test
after_success:
  - coveralls
