language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.5
  - DJANGO=1.6.4
  - DJANGO=1.7.1
install:
  - pip install -q Django==$DJANGO
  - pip install -q nose django-nose
  - pip install -q django-autoslug
  - pip install -q coverage coveralls
  - pip install -e .
script:
  - coverage run --source klingon setup.py test
after_success:
  - coveralls
