language: python

sudo: false

env:
    - TOX_ENV=py27-django1.5
    - TOX_ENV=py27-django1.6
    - TOX_ENV=py27-django1.7
    - TOX_ENV=py27-django1.8
    - TOX_ENV=py34-django1.7
    - TOX_ENV=py34-django1.8

install:
  - pip install tox coverage coveralls

script:
  - coverage erase
  - tox -e $TOX_ENV

after_success:
  - coverage combine
  - coveralls
